import {
  Correction,
  ExamTarget,
  EvidenceItem,
  MaterialItem,
  AbilityBaseline,
  ResourceItem,
  User,
  UserSettings,
} from "@/types";

// ==================== 当前用户 ====================

export const mockUser: User = {
  id: "u-001",
  name: "备考学员",
  avatar: undefined,
  role: "user",
  educationLevel: "middle",
  dailyAvailableTime: 180,
  studyReminderTime: "08:00",
  notificationSettings: {
    studyReminder: true,
    examUpdate: true,
    resourceUpdate: true,
    weeklyReport: true,
  },
  currentExamTargetId: "et-001",
  createdAt: "2026-09-25T08:00:00Z",
  updatedAt: "2026-10-01T08:00:00Z",
};

// ==================== 目标考试 ====================

export const mockExamTargets: ExamTarget[] = [
  {
    id: "et-001",
    userId: "u-001",
    name: "浙江省·杭州市 初中语文 公办学校招聘",
    region: "浙江省 · 杭州市",
    regionCode: "330100",
    province: "浙江省",
    city: "杭州市",
    examType: "public_school",
    educationLevel: "middle",
    year: 2026,
    batch: "上半年统招",
    subject: "chinese",
    stage: "preparation",
    status: "confirmed",
    targetStatus: "announcement",
    isCurrent: true,
    announcementUrl: "https://edu.hangzhou.gov.cn/art/2026/9/1/art_1228920387_58925199.html",
    createdAt: "2026-09-25T08:00:00Z",
    updatedAt: "2026-10-01T08:00:00Z",
  },
  {
    id: "et-002",
    userId: "u-001",
    name: "江苏省·南京市 高中语文 事业单位招聘",
    region: "江苏省 · 南京市",
    regionCode: "320100",
    province: "江苏省",
    city: "南京市",
    examType: "public_institution",
    educationLevel: "high",
    year: 2025,
    batch: "下半年招聘",
    subject: "chinese",
    stage: "completed",
    status: "archived",
    targetStatus: "region",
    isCurrent: false,
    createdAt: "2025-03-10T08:00:00Z",
    updatedAt: "2025-09-01T08:00:00Z",
  },
  // —— 资料模块演示案例：无资料 ——（可在“我的考试”切换为当前目标体验）
  {
    id: "et-demo-mat-none",
    userId: "u-001",
    name: "【演示案例·还没有资料】浙江省·温州市 初中语文 公办学校招聘",
    region: "浙江省 · 温州市",
    regionCode: "330300",
    province: "浙江省",
    city: "温州市",
    examType: "public_school",
    educationLevel: "middle",
    year: 2026,
    batch: "提前批招聘",
    subject: "chinese",
    stage: "preparation",
    status: "confirmed",
    targetStatus: "announcement",
    isCurrent: false,
    createdAt: "2026-09-20T08:00:00Z",
    updatedAt: "2026-09-20T08:00:00Z",
  },
  // —— 资料模块演示案例：多套资料冲突 ——
  {
    id: "et-demo-mat-multi",
    userId: "u-001",
    name: "【演示案例·多套资料冲突】浙江省·宁波市 初中语文 公办学校招聘",
    region: "浙江省 · 宁波市",
    regionCode: "330200",
    province: "浙江省",
    city: "宁波市",
    examType: "public_school",
    educationLevel: "middle",
    year: 2026,
    batch: "上半年统招",
    subject: "chinese",
    stage: "preparation",
    status: "confirmed",
    targetStatus: "announcement",
    isCurrent: false,
    createdAt: "2026-09-22T08:00:00Z",
    updatedAt: "2026-09-22T08:00:00Z",
  },
];

// ==================== 考情证据（字段级结构化证据） ====================
//
// 种子数据模拟“真实后端中已完成人工审核”的状态：
// 只有 official 条目带 reviewerName/reviewedAt；
// 用户新提交公告提取出的结论永远不会自动变成 official。

const ET001_SCOPE = "浙江省杭州市 · 2026年上半年统招 · 初中语文";
const ET001_URL = "https://edu.hangzhou.gov.cn/art/2026/9/1/art_1228920387_58925199.html";

export const mockEvidenceItems: EvidenceItem[] = [
  {
    id: "ev-seed-001",
    examTargetId: "et-001",
    field: "subjects",
    value: "《教育综合知识》、《学科专业知识（初中语文）》",
    reviewStatus: "official",
    sourceName: "杭州市教育局官网",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "笔试科目为《教育综合知识》和《学科专业知识（初中语文）》。",
    scope: ET001_SCOPE,
    updatedAt: "2026-09-28T10:30:00Z",
    reviewerName: "考情审核员（模拟）",
    reviewedAt: "2026-09-28T10:30:00Z",
    version: 1,
  },
  {
    id: "ev-seed-002",
    examTargetId: "et-001",
    field: "exam_scope",
    value:
      "现代汉语基础知识；古代汉语（实词、虚词、句式）；文学常识与作品分析；语文课程标准与教学设计；写作与案例分析",
    reviewStatus: "official",
    sourceName: "杭州市教育局2026年考试大纲",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "学科专业知识考查现代汉语、古代汉语、文学常识、课程标准与教学设计等内容。",
    scope: ET001_SCOPE,
    updatedAt: "2026-09-28T14:00:00Z",
    reviewerName: "考情审核员（模拟）",
    reviewedAt: "2026-09-28T14:00:00Z",
    version: 1,
  },
  {
    id: "ev-seed-003",
    examTargetId: "et-001",
    field: "qualification",
    value: "本科及以上学历；具有相应学段教师资格证；年龄35周岁以下",
    reviewStatus: "official",
    sourceName: "杭州市教育局官网",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "报考人员须本科及以上学历，具有相应学段教师资格证，年龄35周岁以下。",
    scope: ET001_SCOPE,
    updatedAt: "2026-09-28T10:30:00Z",
    reviewerName: "考情审核员（模拟）",
    reviewedAt: "2026-09-28T10:30:00Z",
    version: 1,
  },
  {
    id: "ev-seed-004",
    examTargetId: "et-001",
    field: "registration_time",
    value: "往年多在11月初（如2025年为11月1日—11月7日），2026年待公告确认",
    reviewStatus: "historical",
    sourceName: "2025年杭州市招聘公告",
    sourceType: "historical",
    sourceExcerpt: "2025年报名时间为11月1日9时—11月7日16时。",
    scope: ET001_SCOPE,
    updatedAt: "2026-09-25T08:00:00Z",
    version: 1,
  },
  // —— 以下为“考情审核后台”模块的待审核演示种子 ——
  // 模拟学生提交 2026 年公告后 AI 提取、等待人工审核的状态。
  {
    id: "ev-seed-101",
    examTargetId: "et-001",
    field: "registration_time",
    value: "2026年11月1日9时—11月7日16时",
    reviewStatus: "pending_review",
    sourceName: "杭州市教育局官网",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "报名时间：2026年11月1日9时—11月7日16时，通过网上报名系统注册报名。",
    scope: ET001_SCOPE,
    updatedAt: "2026-10-01T09:00:00Z",
    jobId: "job-seed-demo",
    version: 1,
  },
  {
    id: "ev-seed-102",
    examTargetId: "et-001",
    field: "exam_time",
    value: "2026年12月13日",
    reviewStatus: "pending_review",
    sourceName: "杭州市教育局官网",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "笔试时间：笔试定于2026年12月13日举行，具体时间和地点以准考证为准。",
    scope: ET001_SCOPE,
    updatedAt: "2026-10-01T09:00:00Z",
    jobId: "job-seed-demo",
    version: 1,
  },
  // 分值：两个来源结论不一致 → 来源冲突队列
  {
    id: "ev-seed-103",
    examTargetId: "et-001",
    field: "score",
    value: "两科满分各100分，总分200分",
    reviewStatus: "pending_review",
    sourceName: "杭州市教育局官网",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "笔试科目……两科满分各100分，总分200分。",
    scope: ET001_SCOPE,
    updatedAt: "2026-10-01T09:05:00Z",
    jobId: "job-seed-demo",
    version: 1,
  },
  {
    id: "ev-seed-104",
    examTargetId: "et-001",
    field: "score",
    value: "《学科专业知识》单科满分150分，总分300分",
    reviewStatus: "ai_extracted",
    sourceName: "浙江教师招聘信息网（转载）",
    sourceType: "announcement_url",
    sourceUrl: "https://www.zj-jobs-demo.example.com/2026/hangzhou-teacher",
    sourceExcerpt: "据转载消息，学科专业知识满分150分，两科合计300分。",
    scope: ET001_SCOPE,
    updatedAt: "2026-10-01T09:06:00Z",
    jobId: "job-seed-demo",
    version: 1,
  },
  // 低影响字段：资源审核员也可以审核的示例
  {
    id: "ev-seed-105",
    examTargetId: "et-001",
    field: "education_level",
    value: "初中",
    reviewStatus: "ai_extracted",
    sourceName: "杭州市教育局官网",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "公开招聘初中语文教师12名。",
    scope: ET001_SCOPE,
    updatedAt: "2026-10-01T09:07:00Z",
    jobId: "job-seed-demo",
    version: 1,
  },
];

/** 提交公告表单“填入示例公告”按钮使用的示例文本（含时间/科目/分值/资格条件） */
export const SAMPLE_ANNOUNCEMENT_TEXT = `杭州市教育局2026年上半年公开招聘中小学教师公告
一、招聘岗位：面向社会公开招聘初中语文教师12名。
二、报名时间：2026年11月1日9时—11月7日16时，通过网上报名系统注册报名。
三、笔试时间：笔试定于2026年12月13日举行，具体时间和地点以准考证为准。
四、笔试科目：《教育综合知识》和《学科专业知识（初中语文）》，两科满分各100分，总分200分。
五、报考条件：本科及以上学历；须持有初中及以上语文教师资格证；年龄35周岁以下（1990年11月以后出生）；杭州市户籍优先。
六、考试范围：学科专业知识考查现代汉语、古代汉语、文学常识、语文课程标准与教学设计、写作。`;

// ==================== 用户资料 ====================

// 资料模块演示种子：
// - et-001：一套适用（杭州·初中）
// - et-demo-mat-multi：三套资料冲突（浙江新版 / 全国旧版 / 来源不明扫描件）
// - et-demo-mat-none：不放任何资料，用于“无资料 + 最小资料类别”案例
export const mockMaterials: MaterialItem[] = [
  {
    id: "um-001",
    userId: "u-001",
    examTargetId: "et-001",
    name: "《语文考编通关宝典（浙江专版·初中）》",
    sourceType: "published",
    author: "王某某",
    publisher: "教育出版社",
    applicableRegion: "浙江省",
    year: 2025,
    applicableLevel: "middle",
    coversModules: ["mod_xiandai", "mod_gudai", "mod_wenxue", "mod_jiaoxue", "mod_xiezuo"],
    chapters: [
      { id: "c-001", materialId: "um-001", title: "现代汉语基础", order: 1, isCompleted: true, completedAt: "2026-09-28" },
      { id: "c-002", materialId: "um-001", title: "古代汉语", order: 2, isCompleted: true, completedAt: "2026-09-30" },
      { id: "c-003", materialId: "um-001", title: "文学常识", order: 3, isCompleted: false },
      { id: "c-004", materialId: "um-001", title: "教学设计", order: 4, isCompleted: false },
      { id: "c-005", materialId: "um-001", title: "写作与案例", order: 5, isCompleted: false },
    ],
    catalogConfirmed: true,
    progress: 40,
    note: "学姐推荐的浙江专版，目录已对照2026考纲核对过。",
    createdAt: "2026-09-25T08:00:00Z",
    updatedAt: "2026-10-01T08:00:00Z",
    status: "in_use",
  },
  {
    id: "um-201",
    userId: "u-001",
    examTargetId: "et-demo-mat-multi",
    name: "《浙江省教师招聘考试·语文学科专业知识（2026 浙江专版）》",
    sourceType: "published",
    author: "浙江省教师招聘考试研究组",
    publisher: "浙江教育出版社",
    applicableRegion: "浙江省",
    year: 2026,
    applicableLevel: "middle",
    coversModules: ["mod_xiandai", "mod_gudai", "mod_wenxue", "mod_kebiao", "mod_jiaoxue", "mod_xiezuo"],
    chapters: [
      { id: "c-201-1", materialId: "um-201", title: "现代汉语基础", order: 1, isCompleted: false },
      { id: "c-201-2", materialId: "um-201", title: "古代汉语", order: 2, isCompleted: false },
      { id: "c-201-3", materialId: "um-201", title: "文学常识与作品分析", order: 3, isCompleted: false },
      { id: "c-201-4", materialId: "um-201", title: "语文课程标准解读", order: 4, isCompleted: false },
      { id: "c-201-5", materialId: "um-201", title: "教学设计", order: 5, isCompleted: false },
      { id: "c-201-6", materialId: "um-201", title: "写作与案例分析", order: 6, isCompleted: false },
    ],
    catalogConfirmed: true,
    progress: 35,
    note: "官网购入的新版，浙江专版。",
    createdAt: "2026-09-23T08:00:00Z",
    updatedAt: "2026-09-28T08:00:00Z",
  },
  {
    id: "um-202",
    userId: "u-001",
    examTargetId: "et-demo-mat-multi",
    name: "《教师招聘语文一本通（全国通用版）》",
    sourceType: "institution",
    author: "某培训机构",
    publisher: "培训机构内部发行",
    applicableRegion: "全国",
    year: 2022,
    applicableLevel: "unknown",
    coversModules: ["mod_xiandai", "mod_wenxue", "mod_xiezuo", "mod_zhenti"],
    chapters: [
      { id: "c-202-1", materialId: "um-202", title: "现代汉语考点速记", order: 1, isCompleted: true },
      { id: "c-202-2", materialId: "um-202", title: "文学常识汇编", order: 2, isCompleted: true },
      { id: "c-202-3", materialId: "um-202", title: "写作模板", order: 3, isCompleted: false },
      { id: "c-202-4", materialId: "um-202", title: "全国教师招聘真题选编", order: 4, isCompleted: false },
    ],
    catalogConfirmed: true,
    progress: 60,
    note: "去年备考买的通用版，做了一大半，不确定浙江是否适用。",
    createdAt: "2025-06-10T08:00:00Z",
    updatedAt: "2026-09-15T08:00:00Z",
  },
  {
    id: "um-203",
    userId: "u-001",
    examTargetId: "et-demo-mat-multi",
    name: "《XX机构内部押题资料·语文（完整扫描版）》",
    sourceType: "unknown_scan",
    applicableRegion: "",
    year: 2025,
    applicableLevel: "unknown",
    coversModules: ["mod_jiaoxue", "mod_zhenti", "mod_lianxi"],
    chapters: [
      { id: "c-203-1", materialId: "um-203", title: "教学设计押题十套", order: 1, isCompleted: false },
      { id: "c-203-2", materialId: "um-203", title: "押题卷与参考答案", order: 2, isCompleted: false },
    ],
    catalogConfirmed: false,
    progress: 10,
    note: "网上群里转来的扫描版，没有出版社信息，不知道能不能用。",
    createdAt: "2026-09-26T08:00:00Z",
    updatedAt: "2026-09-26T08:00:00Z",
  },
];

// ==================== 能力基线 ====================

export const mockAbilityBaselines: AbilityBaseline[] = [
  {
    id: "ab-et-001",
    userId: "u-001",
    examTargetId: "et-001",
    inventoryStatus: "single",
    chineseAssessments: [
      { module: "mod_xiandai", level: 3, note: "语法体系基本过完" },
      { module: "mod_gudai", level: 2, note: "虚词和句式经常错" },
      { module: "mod_wenxue", level: 4 },
      { module: "mod_jiaoxue", level: 2, note: "还没开始练" },
      { module: "mod_xiezuo", level: 3 },
    ],
    generalAssessments: [
      { module: "mod_jiaoyuxue", level: 3 },
      { module: "mod_xinlixue", level: 3 },
      { module: "mod_fagui", level: 2 },
    ],
    recentScores: [
      { id: "ps-001", module: "mod_xiandai", scoreText: "72/100", scorePercent: 72, takenAt: "2026-09-27" },
      { id: "ps-002", module: "mod_gudai", scoreText: "55/100", scorePercent: 55, takenAt: "2026-09-29" },
    ],
    weakModules: ["mod_gudai", "mod_jiaoxue"],
    dailyAvailableMinutes: 180,
    weeklyAvailableHours: 12,
    updatedAt: "2026-09-30T12:00:00Z",
  },
  {
    id: "ab-et-demo-mat-multi",
    userId: "u-001",
    examTargetId: "et-demo-mat-multi",
    inventoryStatus: "multiple",
    chineseAssessments: [
      { module: "mod_xiandai", level: 3 },
      { module: "mod_wenxue", level: 3 },
      { module: "mod_jiaoxue", level: 2, note: "几套资料里都有教学设计，不知道跟哪套" },
    ],
    generalAssessments: [],
    recentScores: [],
    weakModules: ["mod_jiaoxue"],
    dailyAvailableMinutes: 120,
    weeklyAvailableHours: 12,
    updatedAt: "2026-09-28T12:00:00Z",
  },
  {
    id: "ab-et-demo-mat-none",
    userId: "u-001",
    examTargetId: "et-demo-mat-none",
    inventoryStatus: "none",
    chineseAssessments: [],
    generalAssessments: [],
    recentScores: [],
    weakModules: [],
    dailyAvailableMinutes: 90,
    weeklyAvailableHours: 8,
    updatedAt: "2026-09-20T12:00:00Z",
  },
];

/** 首次进入时需要由规则层生成诊断快照的演示目标（无资料案例不在其中） */
export const SEEDED_DIAGNOSIS_TARGET_IDS = ["et-001", "et-demo-mat-multi"];

// ==================== 公共资源 ====================

/**
 * 公共资源索引种子（ResourceItem）。
 * 围绕杭州初中 2026 主目标的五个缺口（课标/真题/教育学/心理学/法规）布置匹配案例：
 * - 每个缺口最多 3 条；坏链、权利不明、停用、过期、超期未复核的资源只出现在后台队列，不进推荐；
 * - 所有外部链接均为演示用占位，不提供网盘/付费/全文复制。
 */
export const mockResources: ResourceItem[] = [
  // —— 案例 1：官方大纲（课程标准缺口，全国通用、长期有效） ——
  {
    id: "pr-001",
    title: "《义务教育语文课程标准（2022年版）》",
    description: "教育部发布的义务教育语文课程标准全文，教师招聘语文学科的命题依据。",
    resourceType: "official",
    sourceName: "中华人民共和国教育部",
    sourceUrl: "http://www.moe.gov.cn/srcsite/A26/s8001/202204/t20220420_619921.html",
    rightsStatus: "official",
    applicableRegions: ["全国"],
    applicableLevels: ["primary", "middle", "high"],
    applicableTypes: ["public_school", "private_school", "public_institution", "special_teacher"],
    modules: ["mod_kebiao"],
    recommendReason: "命题依据文件，课标解读类题目的权威出处，建议先通读课程目标与学业质量部分。",
    suggestedChapters: ["第一部分 课程性质与理念", "第三部分 课程目标", "第四部分 课程内容与学业质量"],
    estimatedMinutes: 180,
    lastReviewedAt: "2026-09-20T08:00:00Z",
    linkCheckedAt: "2026-09-20T08:00:00Z",
    linkAlive: true,
    status: "active",
    reviewedBy: "资源审核员C",
    createdAt: "2026-09-20T08:00:00Z",
    updatedAt: "2026-09-20T08:00:00Z",
  },
  // —— 案例 2a：官方招考说明（真题缺口，省级） ——
  {
    id: "pr-005",
    title: "浙江省中小学教师公开招聘笔试说明（语文·含样题）",
    description: "省级教育考试机构发布的笔试说明，含题型、分值结构与官方样题。",
    resourceType: "official",
    sourceName: "浙江省教育考试院",
    sourceUrl: "https://www.example.gov.cn/zhejiang/teacher-exam/2026/bishuo-mock",
    rightsStatus: "official",
    applicableRegions: ["浙江省"],
    year: 2026,
    applicableLevels: ["primary", "middle", "high"],
    applicableTypes: ["public_school", "public_institution"],
    modules: ["mod_zhenti"],
    recommendReason: "省级官方笔试说明与样题，可直接确认杭州岗位的题型与分值结构，优先级最高。",
    suggestedChapters: ["考试形式与试卷结构", "语文样题及参考答案", "命题与答题要求"],
    estimatedMinutes: 120,
    lastReviewedAt: "2026-09-25T08:00:00Z",
    linkCheckedAt: "2026-09-25T08:00:00Z",
    linkAlive: true,
    status: "active",
    reviewedBy: "资源审核员C",
    createdAt: "2026-09-25T08:00:00Z",
    updatedAt: "2026-09-25T08:00:00Z",
  },
  // —— 案例 2b：第三方公开索引（真题缺口，仅原始链接+摘要） ——
  {
    id: "pr-002",
    title: "浙江省教师招聘语文历年题型整理（第三方索引）",
    description: "第三方对 2020-2025 年浙江各地语文学科题型的公开整理，仅索引原始页面与摘要。",
    resourceType: "third_party",
    sourceName: "某教师考试资料公开整理页（第三方）",
    sourceUrl: "https://www.example.com/zhejiang-yuwen-zhenti-index",
    rightsStatus: "third_party",
    applicableRegions: ["浙江省"],
    year: 2025,
    applicableLevels: ["primary", "middle", "high"],
    applicableTypes: ["public_school", "public_institution"],
    modules: ["mod_zhenti"],
    recommendReason: "官方未公布完整真题时的题型补充参考；只索引公开页面，不提供扫描全文，使用时请与官方样题核对。",
    suggestedChapters: ["2023-2025 题型分布表", "阅读理解与写作题示例"],
    estimatedMinutes: 90,
    lastReviewedAt: "2026-09-22T08:00:00Z",
    linkCheckedAt: "2026-09-22T08:00:00Z",
    linkAlive: true,
    status: "active",
    reviewedBy: "资源审核员C",
    createdAt: "2026-09-22T08:00:00Z",
    updatedAt: "2026-09-22T08:00:00Z",
  },
  // —— 非缺口演示：自制学科资料（浏览列表可见，不进入杭州缺口） ——
  {
    id: "pr-003",
    title: "现代汉语语法知识点精讲（平台自制）",
    description: "系统梳理现代汉语语法知识体系，配套章节练习。",
    resourceType: "self_made",
    sourceName: "本平台自制",
    sourceUrl: "/resources/modern-chinese-grammar",
    rightsStatus: "self_made",
    applicableRegions: ["全国"],
    applicableLevels: ["primary", "middle", "high"],
    applicableTypes: ["public_school", "private_school", "public_institution", "special_teacher"],
    modules: ["mod_xiandai"],
    recommendReason: "适合一轮系统过现代汉语语法，配套练习可记录正确率。",
    suggestedChapters: ["词类与短语", "单句与复句", "常见病句辨析"],
    estimatedMinutes: 240,
    lastReviewedAt: "2026-09-15T08:00:00Z",
    linkCheckedAt: "2026-09-15T08:00:00Z",
    linkAlive: true,
    status: "active",
    reviewedBy: "资源审核员C",
    createdAt: "2026-09-15T08:00:00Z",
    updatedAt: "2026-09-15T08:00:00Z",
  },
  {
    id: "pr-004",
    title: "语文教学设计模板与案例库（平台自制）",
    description: "覆盖各学段的教学设计模板与优秀案例拆解。",
    resourceType: "self_made",
    sourceName: "本平台自制",
    sourceUrl: "/resources/teaching-design",
    rightsStatus: "self_made",
    applicableRegions: ["全国"],
    applicableLevels: ["primary", "middle", "high"],
    applicableTypes: ["public_school", "private_school"],
    modules: ["mod_jiaoxue", "mod_jiaocai"],
    recommendReason: "教学设计题的结构化模板与范例，可直接仿写练习。",
    suggestedChapters: ["教学目标三维写法", "阅读课教学设计范例", "板书与作业设计"],
    estimatedMinutes: 200,
    lastReviewedAt: "2026-09-18T08:00:00Z",
    linkCheckedAt: "2026-09-18T08:00:00Z",
    linkAlive: true,
    status: "active",
    reviewedBy: "资源审核员C",
    createdAt: "2026-09-18T08:00:00Z",
    updatedAt: "2026-09-18T08:00:00Z",
  },
  // —— 案例 3a：平台自制（教育学缺口，排在开放资源之前） ——
  {
    id: "pr-101",
    title: "教育综合·教育学基础精讲（平台自制）",
    description: "针对浙江教综科目的教育学基础部分，覆盖课程与教学论、德育、班主任工作。",
    resourceType: "self_made",
    sourceName: "本平台自制",
    sourceUrl: "/resources/general-education",
    rightsStatus: "self_made",
    applicableRegions: ["全国"],
    year: 2026,
    applicableLevels: ["primary", "middle", "high"],
    applicableTypes: ["public_school", "public_institution"],
    modules: ["mod_jiaoyuxue"],
    recommendReason: "按浙江教综考查范围组织，比泛用教材更贴合当前目标，建议作为一轮主干。",
    suggestedChapters: ["教育与教育学", "课程与教学论", "德育与班主任工作"],
    estimatedMinutes: 300,
    lastReviewedAt: "2026-09-18T08:00:00Z",
    linkCheckedAt: "2026-09-18T08:00:00Z",
    linkAlive: true,
    status: "active",
    reviewedBy: "资源审核员C",
    createdAt: "2026-09-18T08:00:00Z",
    updatedAt: "2026-09-18T08:00:00Z",
  },
  // —— 案例 3b：开放授权课件（教育学缺口，第二顺位） ——
  {
    id: "pr-110",
    title: "《教育学基础》开放课程（明确开放授权）",
    description: "高校公开的教育学基础课程课件，页面标注开放学习授权。",
    resourceType: "open",
    sourceName: "某高校开放课程平台",
    sourceUrl: "https://www.example-open.edu.cn/courses/education-basics",
    rightsStatus: "open",
    applicableRegions: ["全国"],
    applicableLevels: ["primary", "middle", "high"],
    applicableTypes: ["public_school", "public_institution"],
    modules: ["mod_jiaoyuxue"],
    recommendReason: "权利状态清晰的开放课件，适合在平台自制讲义之外补充概念讲解。",
    suggestedChapters: ["教育的产生与发展", "教育目的与制度"],
    estimatedMinutes: 240,
    lastReviewedAt: "2026-08-30T08:00:00Z",
    linkCheckedAt: "2026-08-30T08:00:00Z",
    linkAlive: true,
    status: "active",
    reviewedBy: "资源审核员C",
    createdAt: "2026-08-30T08:00:00Z",
    updatedAt: "2026-08-30T08:00:00Z",
  },
  // —— 官方法规条文（法规缺口，长期有效） ——
  {
    id: "pr-103",
    title: "教育法律法规官方条文汇编",
    description: "教师法、义务教育法、未成年人保护法等法规的官方发布页面汇编。",
    resourceType: "official",
    sourceName: "中国人大网 / 教育部",
    sourceUrl: "http://www.example.gov.cn/flfg/jiaoyu-fagui",
    rightsStatus: "official",
    applicableRegions: ["全国"],
    applicableLevels: ["primary", "middle", "high"],
    applicableTypes: ["public_school", "private_school", "public_institution", "special_teacher"],
    modules: ["mod_fagui"],
    recommendReason: "法规题以现行有效条文为准，统一从官方页面学习，避免第三方转述误差。",
    suggestedChapters: ["中华人民共和国教师法", "中华人民共和国义务教育法", "中小学教育惩戒规则（试行）"],
    estimatedMinutes: 150,
    lastReviewedAt: "2026-09-10T08:00:00Z",
    linkCheckedAt: "2026-09-10T08:00:00Z",
    linkAlive: true,
    status: "active",
    reviewedBy: "资源审核员C",
    createdAt: "2026-09-10T08:00:00Z",
    updatedAt: "2026-09-10T08:00:00Z",
  },
  // —— 被过滤候选：坏链 + 权利不明（真题缺口；进入后台“已失效”队列） ——
  {
    id: "pr-201",
    title: "浙江语文真题网盘扫描合集（来源不明）",
    description: "来源不明的完整扫描资料，原始链接已无法访问。",
    resourceType: "third_party",
    sourceName: "匿名网盘分享",
    sourceUrl: "https://pan.example.invalid/s/xxxxxx",
    rightsStatus: "unknown",
    applicableRegions: ["浙江省"],
    year: 2024,
    applicableLevels: ["middle", "high"],
    applicableTypes: ["public_school"],
    modules: ["mod_zhenti"],
    recommendReason: "",
    suggestedChapters: [],
    estimatedMinutes: 0,
    lastReviewedAt: "2026-07-01T08:00:00Z",
    linkCheckedAt: "2026-09-28T08:00:00Z",
    linkAlive: false,
    status: "active",
    createdAt: "2026-07-01T08:00:00Z",
    updatedAt: "2026-09-28T08:00:00Z",
  },
  // —— 被过滤候选：权利不明（心理学缺口；后台“待复核”队列） ——
  {
    id: "pr-202",
    title: "教育心理学“内部押题”讲义（来源不明）",
    description: "聊天群流传的押题讲义，未标注作者与授权。",
    resourceType: "third_party",
    sourceName: "未知（群聊转发）",
    sourceUrl: "https://www.example.com/unknown-yati",
    rightsStatus: "unknown",
    applicableRegions: ["全国"],
    applicableLevels: ["middle"],
    applicableTypes: ["public_school"],
    modules: ["mod_xinlixue"],
    recommendReason: "",
    suggestedChapters: [],
    estimatedMinutes: 0,
    lastReviewedAt: "2026-09-26T08:00:00Z",
    linkCheckedAt: "2026-09-26T08:00:00Z",
    linkAlive: true,
    status: "pending_review",
    createdAt: "2026-09-26T08:00:00Z",
    updatedAt: "2026-09-26T08:00:00Z",
  },
  // —— 已停用的授权资源（心理学缺口；默认不推荐，后台重新启用后才出现） ——
  {
    id: "pr-301",
    title: "教育心理学考点精讲（已授权·当前停用）",
    description: "已获授权的教育心理学考点讲义，因版本更新暂时停用，复核后可恢复。",
    resourceType: "third_party",
    sourceName: "某授权教培内容方",
    sourceUrl: "https://www.example-licensed.cn/xinlixue",
    rightsStatus: "licensed",
    applicableRegions: ["全国"],
    year: 2026,
    applicableLevels: ["primary", "middle", "high"],
    applicableTypes: ["public_school", "public_institution"],
    modules: ["mod_xinlixue"],
    recommendReason: "授权清晰、结构完整；停用期间不产生新推荐，复核新版后可恢复。",
    suggestedChapters: ["认知发展与学习理论", "学习动机与迁移"],
    estimatedMinutes: 210,
    lastReviewedAt: "2026-09-01T08:00:00Z",
    linkCheckedAt: "2026-09-01T08:00:00Z",
    linkAlive: true,
    status: "inactive",
    reviewedBy: "资源审核员C",
    createdAt: "2026-08-20T08:00:00Z",
    updatedAt: "2026-09-28T08:00:00Z",
  },
  // —— 已过失效时间（心理学缺口；后台“已失效”队列） ——
  {
    id: "pr-302",
    title: "教育心理学 2023 旧版串讲（已过适用期）",
    description: "按 2023 考纲录制，标注的适用期已结束。",
    resourceType: "third_party",
    sourceName: "某第三方辅导机构",
    sourceUrl: "https://www.example.com/xinlixue-2023",
    rightsStatus: "third_party",
    applicableRegions: ["全国"],
    year: 2023,
    applicableLevels: ["middle"],
    applicableTypes: ["public_school"],
    modules: ["mod_xinlixue"],
    recommendReason: "旧考纲内容，仅保留索引供对照，适用期已过不再推荐。",
    suggestedChapters: [],
    estimatedMinutes: 120,
    lastReviewedAt: "2026-05-10T08:00:00Z",
    expiresAt: "2026-08-31T23:59:59Z",
    linkCheckedAt: "2026-05-10T08:00:00Z",
    linkAlive: true,
    status: "active",
    reviewedBy: "资源审核员C",
    createdAt: "2026-03-01T08:00:00Z",
    updatedAt: "2026-08-31T00:00:00Z",
  },
  // —— 超期未复核（后台“待复核”队列；不进缺口推荐） ——
  {
    id: "pr-303",
    title: "教学设计常见题型开放资料（超过 180 天未复核）",
    description: "开放授权资料，但链接与内容已超过复核周期未确认。",
    resourceType: "open",
    sourceName: "某教师学习开放社区",
    sourceUrl: "https://www.example-open.org/jiaoxue-tixing",
    rightsStatus: "open",
    applicableRegions: ["全国"],
    applicableLevels: ["middle"],
    applicableTypes: ["public_school"],
    modules: ["mod_jiaoxue"],
    recommendReason: "可供补充练习；因长期未复核，链接有效性需重新确认后才恢复推荐。",
    suggestedChapters: ["教学设计题型汇总"],
    estimatedMinutes: 90,
    lastReviewedAt: "2025-12-10T08:00:00Z",
    linkCheckedAt: "2025-12-10T08:00:00Z",
    linkAlive: true,
    status: "active",
    createdAt: "2025-12-10T08:00:00Z",
    updatedAt: "2025-12-10T08:00:00Z",
  },
];

// ==================== 纠错治理 ====================
//
// 纠错种子（u-001 提交）：
// - cor-seed-001：针对分值冲突结论的新纠错（已提交，等待后台处理）
// - cor-seed-002：资格条件纠错，审核员已要求补充（待补充，用户可继续举证）
// 旧 localStorage 中没有 kb_corrections 数据时才会播种；在设置页清除数据后可见。

const correctionSeedNow = "2026-10-01T09:20:00Z";

export const mockCorrections: Correction[] = [
  {
    id: "cor-seed-001",
    userId: "u-001",
    targetType: "evidence",
    examTargetId: "et-001",
    evidenceItemId: "ev-seed-103",
    field: "score",
    fieldLabel: "分值",
    subject: "分值",
    currentValue: "两科满分各100分，总分200分",
    description:
      "我在杭州市教育局官网看到的2026年新版公告里，学科专业知识满分是150分，和画像里的100分不一致，请核对。",
    suggestedValue: "《学科专业知识》单科满分150分，两科总分300分",
    sources: [
      {
        id: "cor-src-seed-001",
        url: ET001_URL,
        note: "杭州市教育局2026年招聘公告附件1笔试安排",
        createdAt: correctionSeedNow,
      },
    ],
    status: "submitted",
    timeline: [
      {
        id: "cor-tl-seed-001",
        at: correctionSeedNow,
        actorId: "u-001",
        actorName: "备考学员",
        actorRole: "user",
        action: "submit",
      },
    ],
    createdAt: correctionSeedNow,
    updatedAt: correctionSeedNow,
  },
  {
    id: "cor-seed-002",
    userId: "u-001",
    targetType: "evidence",
    examTargetId: "et-001",
    evidenceItemId: "ev-seed-003",
    field: "qualification",
    fieldLabel: "资格条件",
    subject: "资格条件",
    currentValue: "本科及以上学历；具有相应学段教师资格证；年龄35周岁以下",
    description: "公告里好像还写了杭州户籍优先，不确定是否影响资格条件，想请审核员确认。",
    suggestedValue: "补充“杭州市户籍优先”相关表述",
    sources: [
      {
        id: "cor-src-seed-002",
        url: ET001_URL,
        note: "公告第五条报考条件",
        createdAt: "2026-09-30T12:00:00Z",
      },
    ],
    status: "need_info",
    resultNote: "请补充公告原文中关于户籍要求的完整表述或截图链接，目前提供的链接中未能定位到该条款。",
    handlerId: "u-002",
    handlerName: "考情审核员",
    handledAt: "2026-10-01T10:00:00Z",
    timeline: [
      {
        id: "cor-tl-seed-002-1",
        at: "2026-09-30T12:00:00Z",
        actorId: "u-001",
        actorName: "备考学员",
        actorRole: "user",
        action: "submit",
      },
      {
        id: "cor-tl-seed-002-2",
        at: "2026-10-01T09:40:00Z",
        actorId: "u-002",
        actorName: "考情审核员",
        actorRole: "exam_reviewer",
        action: "start_processing",
      },
      {
        id: "cor-tl-seed-002-3",
        at: "2026-10-01T10:00:00Z",
        actorId: "u-002",
        actorName: "考情审核员",
        actorRole: "exam_reviewer",
        action: "request_info",
        note: "请补充公告原文中关于户籍要求的完整表述或截图链接，目前提供的链接中未能定位到该条款。",
      },
    ],
    createdAt: "2026-09-30T12:00:00Z",
    updatedAt: "2026-10-01T10:00:00Z",
  },
];

// ==================== 本周计划 ====================
// ==================== 用户设置 ====================

export const mockUserSettings: UserSettings = {
  educationLevel: "middle",
  dailyAvailableTime: 180,
  studyReminderTime: "08:00",
  notifications: {
    studyReminder: true,
    examUpdate: true,
    resourceUpdate: true,
    weeklyReport: true,
  },
};

// ==================== 本地存储键名 ====================

export const STORAGE_KEYS = {
  SESSION: "kb_session",
  USER: "kb_user",
  EXAM_TARGETS: "kb_exam_targets",
  EVIDENCE_ITEMS: "kb_evidence_items",
  EXTRACTION_JOBS: "kb_extraction_jobs",
  CORRECTIONS: "kb_corrections",
  REVIEW_LOGS: "kb_review_logs",
  MATERIALS: "kb_materials",
  ABILITY_BASELINES: "kb_ability_baselines",
  MATERIAL_DIAGNOSES: "kb_material_diagnoses",
  RESOURCES: "kb_public_resources",
  RESOURCE_VIEWS: "kb_resource_views",
  RESOURCE_PLAN_LINKS: "kb_resource_plan_links",
  PLANS: "kb_plans",
  DAILY_PLANS: "kb_daily_plans",
  TASK_FEEDBACKS: "kb_task_feedbacks",
  PLAN_ADJUSTMENTS: "kb_plan_adjustments",
  WEEKLY_REVIEWS: "kb_weekly_reviews",
  // —— 治理模块：通知偏好 / 站内通知 / 数据删除申请 / 结论撤回留痕 ——
  NOTIFICATION_PREFS: "kb_notification_prefs",
  NOTIFICATIONS: "kb_notifications",
  DELETION_REQUESTS: "kb_deletion_requests",
  RETRACTION_LOGS: "kb_retraction_logs",
  // —— 数据指标与异常监控：统一分析事件流（live 真实操作 + seed 演示种子） ——
  ANALYTICS_EVENTS: "kb_analytics_events",
  // —— v6.1 模块 9：未登录访客在画像阶段产生的待迁移事件，登录后一次性归属到真实账号 ——
  GUEST_ANALYTICS_PENDING: "kb_guest_analytics_pending",
  SETTINGS: "kb_settings",
  // —— v5.1 首次体验：未登录访客的三步问答进度与结果（仅本机浏览器，7 天过期） ——
  GUEST_SESSION: "kb_guest_session",
  // —— v6.1 首次体验：未登录访客的五组基础画像与初步机会结果（与旧键隔离，7 天过期） ——
  GUEST_PROFILE_V61: "kb_guest_profile_v61",
  // —— v6.1 模块 5：登录后按机会补问的条件事实（年龄/户籍/社保/经历/特有条件答案），随画像提交后端重算 ——
  PROFILE_SUPPLEMENT_V61: "kb_profile_supplement_v61",
  // —— 模块 7：主要目标考试内容的人工确认记录（绑定机会单元 + 公告版本，版本变更即失效） ——
  EXAM_CONTENT_CONFIRMATIONS: "kb_exam_content_confirmations",
} as const;
